### PR TITLE
Pin gazebo7.7

### PR DESCRIPTION
**Pull request by dhood**
We need to pin 7.7 because since the release of 7.8 logging of the ur10 doesn't work: https://bitbucket.org/osrf/ariac/issues/78

### CODE REVIEW

**Comment by dhood** [comment]
Something is still a bit off. For one thing, startup of gazebo or log playback has a longer load time than it used to.

More concerning is that the `example_trial1` config file causes playback of logs to have:

```
process[gazebo-2]: started with pid [12423]
Gazebo multi-robot simulator, version 7.7.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Wrn] [LogPlay.cc:301] Unable to find <sim_time> tags in any chunk.
[Wrn] [LogPlay.cc:328] Unable to find <sim_time>...</sim_time> tags in the last chunk.
[Wrn] [LogPlay.cc:373] Unable to find <iterations>...</iterations> tags in the first chunk. Assuming that the first <iterations> value is 0.
[Wrn] [msgs.cc:1807] Conversion of sensor type[logical_camera] not suppported.
```

which happens if nothing in the simulation moves (the example team's node should cause the robot to move). this is reproducible, for both example team 1 & 2 (indigo and kinetic, respectively).

Sometimes (not always) the kinetic server dies before the competitor nodes startup. Usually the competitor nodes are the ones that cause the server to die (by ending the competition after 10s)...

**Comment by j-rivero** [comment]
> Something is still a bit off

We have changed the gazebo version (reverted by this PR) and the gazebo_ros_pkgs code (from packages to source build from a branch). 

> config file causes playback of logs to have

These seems errors coming directly from gazebo. They could come from a corrupted log file as result of not properly stop the recording before kill the simulator (or any other reason). Is the error reproducible?

> Sometimes (not always) the kinetic server dies before the competitor nodes startup. Usually the competitor nodes are the ones that cause the server to die (by ending the competition after 10s)...

Is this something that appeared after the latest changes? Could be verify if using the previous version (docker with gazebo_ros_pkgs) the error does not appeared or it is also there? Any clue in the logs about what it is dying?

**Comment by dhood** [comment]
> We have changed the gazebo version (reverted by this PR) and the gazebo_ros_pkgs code (from packages to source build from a branch). 

The custom gazebo_ros_pkgs change was implemented + tested with gazebo 7.7 before gazebo 7.8 was released, so shouldn't be the issue

> Is this something that appeared after the latest changes? Could be verify if using the previous version (docker with gazebo_ros_pkgs) the error does not appeared or it is also there? Any clue in the logs about what it is dying?

Only on this branch. On master (which uses gazebo 7.8 now) there's no communication issue like this (it's just the gz logging insertion issue). I haven't investigated heaps yet (it was late), but I saw an error in the competitor container that it couldn't connect to the ros master (which is in the server container). I think the competitor container trying to connect to the server is what's causing the system to die. The competitor container will have gazebo 7.8 installed (as a dependency of ariac) but I wouldn't think that that version difference would matter since it's only meant to be ROS communication between them... I'll keep investigating.

> These seems errors coming directly from gazebo. They could come from a corrupted log file as result of not properly stop the recording before kill the simulator (or any other reason). Is the error reproducible?

I believe this is just a side effect of the above point, not a gazebo logging issue. It is reliably reproducible on indigo + kinetic on two different machines, but only with example_trial1. That trial does not use the conveyor belt (example_trial2 does), so if the competitor code is not connecting and controlling the robot, nothing is moving in the environment and the log doesn't have anything to record. For example_trial2, even if the competitor doesn't move the robot, the conveyor belt will still move, so that's why those logs are playable. If I'm correct this issue will go away once we get the competitor to move the arm.

**Comment by dhood** [comment]
I believe I've fixed this branch now. The crash when the user container started up was caused by the user calling the start_competition service too early. (Well, actually, the server is advertising the service too early).

Increasing this delay fixes it: https://github.com/osrf/ariac-docker/pull/12/commits/2d96cf9eaefed0cb842438de61662186c08c7b2e

Another issue is that the machines I was testing with didn't have clean caches. I didn't think that would be an issue since as of https://github.com/osrf/ariac-docker/pull/10/commits/4e62fdb9414fbdd0cd15bd3822f30bf5e485cee9 the cache is not used by default. However, there was a bug in that commit due to a rebase and the `--no-cache` flag wasn't being passed through (fixed in https://github.com/osrf/ariac-docker/pull/12/commits/968fa9d11cdcd523ce68510f57ddb152ceac21cd). So, the competitor images were using outdated ARIAC version, and updating them seems to fix the empty logs

**Comment by dhood** [comment]
I've tested on more machines now, and have still seen the 
```
[Wrn] [LogPlay.cc:301] Unable to find <sim_time> tags in any chunk.
[Wrn] [LogPlay.cc:328] Unable to find <sim_time>...</sim_time> tags in the last chunk.
[Wrn] [LogPlay.cc:373] Unable to find <iterations>...</iterations> tags in the first chunk. Assuming that the first <iterations> value is 0.
[Wrn] [msgs.cc:1807] Conversion of sensor type[logical_camera] not suppported.
```
issue in log playback, but the containers are definitely communicating and the competitor nodes are trying to move the arm. I think it might just be that the arm hits the logical camera and so doesn't move "enough" to trigger logging. I moved the logical camera out of the way and now the arm can swing around and if that was the reason, it should be fixed now.

Feeling more confident about this branch after testing on different machines and will merge. gazebo 7.8.1 can play back 7.7 logs, users won't need to downgrade.

**Pull request merged**
